scimify:
  build: .
  ports:
    - "9080:80"
  volumes:
    - .:/var/www/html/
  links:
    - scimify_db
scimify_db:
  image: mysql:5.7
  ports:
    - "3333:3306"
  environment:
       - MYSQL_ROOT_PASSWORD=Passw0rd!
       - MYSQL_DATABASE=scimify